use std::fs;
use std::path::Path;
use std::sync::RwLock;

use crate::error::{Aria2Error, Result};
use crate::http::cookie::Cookie;

pub struct CookieStorage {
    cookies: RwLock<Vec<Cookie>>,
}

impl CookieStorage {
    pub fn new() -> Self {
        Self { cookies: RwLock::new(Vec::new()) }
    }

    pub fn add(&self, cookie: Cookie) {
        let mut cookies = self.cookies.write().unwrap();
        if let Some(pos) = cookies.iter().position(|c| c == &cookie) {
            cookies[pos] = cookie;
        } else {
            cookies.push(cookie);
        }
    }

    pub fn find_cookies(&self, host: &str, path: &str, secure: bool) -> Vec<Cookie> {
        let cookies = self.cookies.read().unwrap();
        let date = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs() as i64;
        cookies.iter()
            .filter(|c| c.match_request(host, path, date, secure))
            .cloned()
            .collect()
    }

    pub fn find_cookies_for_url(&self, url: &reqwest::Url) -> Vec<Cookie> {
        let host = url.host_str().unwrap_or("");
        let path = url.path();
        let scheme = url.scheme();
        let secure = scheme == "https";
        self.find_cookies(host, path, secure)
    }

    pub fn expire_cookies(&self, base_time: i64) -> usize {
        let mut cookies = self.cookies.write().unwrap();
        let before = cookies.len();
        cookies.retain(|c| !c.is_expired(base_time));
        before - cookies.len()
    }

    pub fn count(&self) -> usize {
        self.cookies.read().unwrap().len()
    }

    pub fn load_file(&self, path: &Path) -> Result<usize> {
        let data = fs::read_to_string(path).map_err(|e| Aria2Error::Io(e.to_string()))?;
        let parsed = crate::http::ns_cookie_parser::NsCookieParser::parse_str(&data)?;
        let n = parsed.len();
        let mut cookies = self.cookies.write().unwrap();
        for cookie in parsed {
            if let Some(pos) = cookies.iter().position(|c| *c == cookie) {
                cookies[pos] = cookie;
            } else {
                cookies.push(cookie);
            }
        }
        Ok(n)
    }

    pub fn save_file(&self, path: &Path) -> Result<()> {
        let cookies = self.cookies.read().unwrap();
        let mut lines = Vec::with_capacity(cookies.len() + 3);
        lines.push("# Netscape HTTP Cookie File".to_string());
        lines.push("# This file is generated by aria2-rust".to_string());
        for c in cookies.iter() {
            lines.push(c.to_netscape_line());
        }
        fs::write(path, lines.join("\n")).map_err(|e| Aria2Error::Io(e.to_string()))?;
        Ok(())
    }

    pub fn clear(&self) {
        self.cookies.write().unwrap().clear();
    }

    pub fn to_header_string(&self, host: &str, path: &str, secure: bool) -> String {
        let cookies = self.find_cookies(host, path, secure);
        if cookies.is_empty() { return String::new(); }
        cookies.iter().map(|c| format!("{}={}", c.name, c.value)).collect::<Vec<_>>().join("; ")
    }

    pub fn is_empty(&self) -> bool {
        self.cookies.read().unwrap().is_empty()
    }
}

impl Default for CookieStorage {
    fn default() -> Self { Self::new() }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_creation_and_count() {
        let store = CookieStorage::new();
        assert_eq!(store.count(), 0);
        assert!(store.is_empty());
    }

    #[test]
    fn test_add_cookie() {
        let store = CookieStorage::new();
        store.add(Cookie::new("sid", "v1", "example.com"));
        assert_eq!(store.count(), 1);
        assert!(!store.is_empty());
    }

    #[test]
    fn test_add_updates_existing() {
        let store = CookieStorage::new();
        store.add(Cookie::new("sid", "old", "example.com"));
        store.add(Cookie::new("sid", "new", "example.com"));
        assert_eq!(store.count(), 1);

        let found = store.find_cookies("example.com", "/", false);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].value, "new");
    }

    #[test]
    fn test_find_cookies_filters() {
        let store = CookieStorage::new();
        store.add(Cookie::new("a", "1", "example.com"));
        store.add(Cookie::new("b", "2", "other.com"));

        let found = store.find_cookies("example.com", "/", false);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].name, "a");
    }

    #[test]
    fn test_find_cookies_for_url() {
        let store = CookieStorage::new();
        let mut c = Cookie::new("lang", "en", "example.com");
        c.path = "/api".to_string();
        store.add(c);

        let url = reqwest::Url::parse("http://example.com/api/data").unwrap();
        let found = store.find_cookies_for_url(&url);
        assert_eq!(found.len(), 1);

        let url2 = reqwest::Url::parse("http://example.com/home").unwrap();
        let found2 = store.find_cookies_for_url(&url2);
        assert!(found2.is_empty());
    }

    #[test]
    fn test_expire_cookies() {
        let store = CookieStorage::new();
        let mut expired = Cookie::new("old", "v", "x.com");
        expired.persistent = true;
        expired.expiry_time = 1;
        store.add(expired);

        let mut fresh = Cookie::new("fresh", "v", "x.com");
        fresh.persistent = true;
        fresh.expiry_time = i64::MAX;
        store.add(fresh);

        assert_eq!(store.count(), 2);
        let removed = store.expire_cookies(2);
        assert_eq!(removed, 1);
        assert_eq!(store.count(), 1);
    }

    #[test]
    fn test_clear() {
        let store = CookieStorage::new();
        store.add(Cookie::new("a", "1", "b.com"));
        store.add(Cookie::new("c", "2", "d.com"));
        store.clear();
        assert_eq!(store.count(), 0);
    }

    #[test]
    fn test_to_header_string() {
        let store = CookieStorage::new();
        store.add(Cookie::new("a", "1", "example.com"));
        store.add(Cookie::new("b", "2", "example.com"));

        let hdr = store.to_header_string("example.com", "/", false);
        assert!(hdr.contains("a=1"));
        assert!(hdr.contains("b=2"));
    }

    #[test]
    fn test_to_header_string_empty_for_no_match() {
        let store = CookieStorage::new();
        store.add(Cookie::new("a", "1", "example.com"));
        let hdr = store.to_header_string("other.com", "/", false);
        assert!(hdr.is_empty());
    }

    #[test]
    #[ignore]
    fn test_load_save_roundtrip() {
        let dir = std::env::temp_dir().join("aria2_test_cookie");
        fs::create_dir_all(&dir).ok();
        let path = dir.join("cookies.txt");

        let store = CookieStorage::new();
        store.add(Cookie::new("sid", "abc", "example.com"));
        store.save_file(&path).expect("save should succeed");

        let store2 = CookieStorage::new();
        let n = store2.load_file(&path).expect("load should succeed");
        assert_eq!(n, 1);

        let found = store2.find_cookies("example.com", "/", false);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].value, "abc");

        fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn test_multiple_domains_independent() {
        let store = CookieStorage::new();
        store.add(Cookie::new("a", "1", "alpha.com"));
        store.add(Cookie::new("b", "2", "beta.com"));
        store.add(Cookie::new("c", "3", "alpha.com"));

        assert_eq!(store.count(), 3);
        assert_eq!(store.find_cookies("alpha.com", "/", false).len(), 2);
        assert_eq!(store.find_cookies("beta.com", "/", false).len(), 1);
    }
}
