use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::path::PathBuf;
use tracing::{debug, info};

#[derive(Debug, Clone)]
pub struct Cookie {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    pub expires: Option<i64>,
    pub secure: bool,
    pub http_only: bool,
}

impl Cookie {
    pub fn new(name: &str, value: &str) -> Self {
        Self {
            name: name.to_string(),
            value: value.to_string(),
            domain: String::new(),
            path: "/".to_string(),
            expires: None,
            secure: false,
            http_only: false,
        }
    }

    pub fn matches_domain(&self, domain: &str) -> bool {
        if self.domain.is_empty() {
            return true;
        }
        if self.domain.starts_with('.') {
            domain.ends_with(&self.domain) || domain == &self.domain[1..]
        } else {
            domain == self.domain
        }
    }

    pub fn matches_path(&self, path: &str) -> bool {
        if self.path.is_empty() {
            return true;
        }
        path.starts_with(&self.path)
    }

    pub fn is_expired(&self, timestamp: i64) -> bool {
        match self.expires {
            Some(exp) => exp > 0 && exp <= timestamp,
            None => false,
        }
    }

    pub fn to_header_string(&self) -> String {
        format!("{}={}", self.name, self.value)
    }
}

pub struct CookieJar {
    cookies: Vec<Cookie>,
    file_path: Option<PathBuf>,
}

impl CookieJar {
    pub fn new() -> Self {
        Self {
            cookies: Vec::new(),
            file_path: None,
        }
    }

    pub fn with_file(path: PathBuf) -> Result<Self, String> {
        let mut jar = Self::new();
        jar.file_path = Some(path.clone());
        jar.load_from_file(&path)?;
        Ok(jar)
    }

    pub fn add_cookie(&mut self, cookie: Cookie) {
        self.cookies
            .retain(|c| c.name != cookie.name || c.domain != cookie.domain);
        self.cookies.push(cookie);
    }

    pub fn add_from_set_cookie_header(&mut self, set_cookie: &str, default_domain: &str) {
        if let Some(cookie) = Self::parse_set_cookie(set_cookie, default_domain) {
            debug!(
                "添加Cookie: {}={} (domain={})",
                cookie.name, cookie.value, cookie.domain
            );
            self.add_cookie(cookie);
        }
    }

    pub fn get_cookies_for_request(&self, domain: &str, path: &str) -> Vec<Cookie> {
        let now = chrono_lite_timestamp();
        self.cookies
            .iter()
            .filter(|c| c.matches_domain(domain) && c.matches_path(path) && !c.is_expired(now))
            .cloned()
            .collect()
    }

    pub fn get_cookie_header(&self, domain: &str, path: &str) -> Option<String> {
        let matching = self.get_cookies_for_request(domain, path);
        if matching.is_empty() {
            return None;
        }
        let header: Vec<String> = matching.iter().map(|c| c.to_header_string()).collect();
        Some(header.join("; "))
    }

    pub fn save(&self) -> Result<(), String> {
        let path = self.file_path.as_ref().ok_or("未设置Cookie文件路径")?;
        Self::save_to_file(path, &self.cookies)
    }

    pub fn load(&mut self) -> Result<(), String> {
        let path = self
            .file_path
            .as_ref()
            .ok_or("未设置Cookie文件路径")?
            .clone();
        self.load_from_file(&path)
    }

    fn load_from_file(&mut self, path: &PathBuf) -> Result<(), String> {
        if !path.exists() {
            info!("Cookie文件不存在，创建空CookieJar: {:?}", path);
            return Ok(());
        }

        let file = fs::File::open(path).map_err(|e| format!("打开Cookie文件失败: {}", e))?;
        let reader = BufReader::new(file);

        for line in reader.lines() {
            let line = line.map_err(|e| format!("读取Cookie文件失败: {}", e))?;
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(cookie) = Self::parse_mozilla_line(line) {
                self.cookies.push(cookie);
            }
        }

        info!("从文件加载了 {} 个Cookie: {:?}", self.cookies.len(), path);
        Ok(())
    }

    fn save_to_file(path: &PathBuf, cookies: &[Cookie]) -> Result<(), String> {
        let mut file = fs::File::create(path).map_err(|e| format!("创建Cookie文件失败: {}", e))?;

        writeln!(file, "# Netscape HTTP Cookie File").map_err(|e| format!("写入失败: {}", e))?;
        writeln!(file, "# https://curl.se/docs/http-cookies.html")
            .map_err(|e| format!("写入失败: {}", e))?;
        writeln!(file, "# This file was generated by aria2-rust")
            .map_err(|e| format!("写入失败: {}", e))?;

        for cookie in cookies {
            let domain_flag = if cookie.domain.starts_with('.') {
                ".TRUE."
            } else {
                ".FALSE."
            };
            let secure = if cookie.secure { ".TRUE." } else { ".FALSE." };
            let expires = cookie.expires.unwrap_or(0);
            writeln!(
                file,
                "\t{}\t{}\t{}\t{}\t{}\t{}\t{}",
                domain_flag, cookie.domain, secure, cookie.path, expires, cookie.name, cookie.value
            )
            .map_err(|e| format!("写入Cookie失败: {}", e))?;
        }

        info!("保存了 {} 个Cookie到文件: {:?}", cookies.len(), path);
        Ok(())
    }

    fn parse_mozilla_line(line: &str) -> Option<Cookie> {
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 7 {
            return None;
        }

        Some(Cookie {
            name: fields[5].to_string(),
            value: fields[6].to_string(),
            domain: fields[1].trim_start_matches('.').to_string(),
            path: fields[3].to_string(),
            expires: fields[4].parse::<i64>().ok(),
            secure: fields[2].eq_ignore_ascii_case(".TRUE."),
            http_only: false,
        })
    }

    fn parse_set_cookie(set_cookie: &str, default_domain: &str) -> Option<Cookie> {
        let parts: Vec<&str> = set_cookie.split(';').collect();
        if parts.is_empty() {
            return None;
        }

        let nv_pair = parts[0].split_once('=')?;
        let name = nv_pair.0.trim().to_string();
        let value = nv_pair.1.trim().to_string();

        let mut cookie = Cookie::new(&name, &value);
        cookie.domain = default_domain.to_string();

        for attr in &parts[1..] {
            let attr = attr.trim();
            if let Some((key, val)) = attr.split_once('=') {
                match key.trim().to_lowercase().as_str() {
                    "domain" => cookie.domain = val.trim().to_string(),
                    "path" => cookie.path = val.trim().to_string(),
                    "expires" | "max-age" => {
                        if let Ok(secs) = val.trim().parse::<i64>() {
                            cookie.expires = Some(secs);
                        }
                    }
                    _ => {}
                }
            } else {
                match attr.to_lowercase().as_str() {
                    "secure" => cookie.secure = true,
                    "httponly" => cookie.http_only = true,
                    _ => {}
                }
            }
        }

        Some(cookie)
    }

    pub fn len(&self) -> usize {
        self.cookies.len()
    }

    pub fn is_empty(&self) -> bool {
        self.cookies.is_empty()
    }

    pub fn clear_expired(&mut self) {
        let now = chrono_lite_timestamp();
        let before = self.cookies.len();
        self.cookies.retain(|c| !c.is_expired(now));
        let removed = before - self.cookies.len();
        if removed > 0 {
            debug!("清理了 {} 个过期Cookie", removed);
        }
    }
}

fn chrono_lite_timestamp() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}

impl Default for CookieJar {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cookie_creation() {
        let cookie = Cookie::new("session_id", "abc123");
        assert_eq!(cookie.name, "session_id");
        assert_eq!(cookie.value, "abc123");
    }

    #[test]
    fn test_cookie_domain_matching() {
        let cookie = Cookie::new("test", "value");
        assert!(cookie.matches_domain("example.com"));

        let subdomain_cookie = Cookie {
            name: "test".into(),
            value: "val".into(),
            domain: ".example.com".into(),
            path: "/".into(),
            expires: None,
            secure: false,
            http_only: false,
        };
        assert!(subdomain_cookie.matches_domain("www.example.com"));
        assert!(subdomain_cookie.matches_domain("example.com"));
        assert!(!subdomain_cookie.matches_domain("other.com"));
    }

    #[test]
    fn test_cookie_jar_operations() {
        let mut jar = CookieJar::new();
        jar.add_cookie(Cookie::new("cookie1", "value1"));
        jar.add_cookie(Cookie::new("cookie2", "value2"));
        assert_eq!(jar.len(), 2);

        let header = jar.get_cookie_header("example.com", "/");
        assert!(header.is_some());
        assert!(header.unwrap().contains("cookie1"));
    }

    #[test]
    fn test_parse_set_cookie() {
        let set_cookie = "session=abc123; Domain=.example.com; Path=/; Secure";
        let cookie = CookieJar::parse_set_cookie(set_cookie, "example.com");
        assert!(cookie.is_some());
        let c = cookie.unwrap();
        assert_eq!(c.name, "session");
        assert_eq!(c.value, "abc123");
        assert!(c.secure);
    }

    #[test]
    fn test_mozilla_format_parsing() {
        let line = ".FALSE.\texample.com\t.FALSE\t/\t0\tname\tvalue";
        let cookie = CookieJar::parse_mozilla_line(line);
        assert!(cookie.is_some());
        let c = cookie.unwrap();
        assert_eq!(c.name, "name");
        assert_eq!(c.value, "value");
        assert_eq!(c.domain, "example.com");
    }
}
